#ifndef _GRAMSCHM_CUH
#define _GRAMSCHM_CUH

#ifdef MINI_DATASET
// # define ...
#elif defined(SMALL_DATASET)
// # define ...
#elif defined(MEDIUM_DATASET)
// # define ...
#elif defined(LARGE_DATASET)
// # define ...
#elif defined(EXTRALARGE_DATASET)
// # define ...
#endif

#endif // _GRAMSCHM_CUH
