#ifndef _MVT_CUH
#define _MVT_CUH

#ifdef MINI_DATASET
// # define ...
#elif defined(SMALL_DATASET)
// # define ...
#elif defined(MEDIUM_DATASET)
// # define ...
#elif defined(LARGE_DATASET)
// # define ...
#elif defined(EXTRALARGE_DATASET)
// # define ...
#endif

#endif // _MVT_CUH
